import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTENT_DIR = ROOT / "content" / "publications"
OUTPUT = ROOT / "_pages" / "includes" / "pub.md"


def read_json(path):
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def read_text(path):
    return path.read_text(encoding="utf-8").strip()


def project_html(project_dir):
    meta = read_json(project_dir / "metadata.json")
    description = read_text(project_dir / "description.md")

    image = meta["image"].lstrip("/")
    badge = meta["badge"]
    title = meta["title"]
    url = meta["url"]
    authors = meta["authors"]
    alt = meta.get("image_alt", title)

    return f"""<div class='paper-box'><div class='paper-box-image'><div><div class="badge">{badge}</div><img src='{{{{ "/{image}" | relative_url }}}}' alt="{alt}" width="100%"></div></div>
<div class='paper-box-text' markdown="1">

[{title}]({url}) \\\\
{authors}

{description}

</div>
</div>"""


def main():
    manifest = read_json(CONTENT_DIR / "manifest.json")
    projects = []
    for project_name in manifest["projects"]:
        project_dir = CONTENT_DIR / project_name
        meta = read_json(project_dir / "metadata.json")
        projects.append((project_name, meta))

    sections = {}
    for project_name, meta in projects:
        sections.setdefault(meta["section"], []).append(project_name)

    lines = [
        "<!-- This file is generated by scripts/build_publications.py. -->",
        "<!-- Edit content/publications/* instead of editing this file directly. -->",
        "",
        "# Publications",
        manifest["intro"],
        "",
        manifest["note"],
        "",
    ]

    for section in manifest["section_order"]:
        lines.append(f"## {section}")
        lines.append("")
        for project_name in sections.get(section, []):
            lines.append(project_html(CONTENT_DIR / project_name))
            lines.append("")

    OUTPUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
